FROM node:20-alpine

WORKDIR /app

# Copy minimal files to build and run
COPY package*.json ./
RUN npm ci --omit=dev || npm install --omit=dev

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm","start"]

