name: "Feature Request"
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Describe the feature you'd like to see implemented.

  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Which project is this feature for?
      options:
        - helios
        - welcome (too.foo)
        - autocrate
        - chladni
        - portfolio
        - blog
        - mcad
        - ecad
        - infra
        - core
        - storage-server
    validations:
      required: true

  - type: checkboxes
    id: automation
    attributes:
      label: Enable Claude Automation
      description: Let Claude agents automatically implement this feature
      options:
        - label: "Enable automation (adds `claude-auto` label)"
          required: false

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      options:
        - New feature
        - UI/UX improvement
        - Performance optimization
        - Refactor
        - Documentation
        - CI/CD
        - Other
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What do you want to add or improve?
      placeholder: Describe the feature clearly
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: Explain the use case or pain point
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What defines "done" for this feature?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Tests pass
    validations:
      required: false

  - type: checkboxes
    id: affected
    attributes:
      label: Affected Projects
      description: Check all that apply (for cross-project features)
      options:
        - label: core
        - label: helios
        - label: too.foo
        - label: storage-server
        - label: simulation-cli

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ### How Automation Works

        **With automation enabled:**
        1. Claude reads your issue (within 60 seconds)
        2. Investigates code and proposes solutions
        3. Deploys previews to `p.{project}.too.foo`
        4. Comment naturally to iterate: "make it bigger", "ship it!"
