//! G-code export for CNC machining

use crate::manufacturing::cnc::*;

/// G-code unit modes
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GcodeUnits {
    Metric,   // G21 - millimeters
    Imperial, // G20 - inches
}

/// Export CNC program to G-code
pub fn export_cnc_gcode(program: &CncCutProgram, units: GcodeUnits) -> String {
    let mut gcode = String::new();

    // Header comments
    gcode.push_str("(AutoCrate CNC Program)\n");
    gcode.push_str(&format!("(Material: {})\n", program.material_setup));
    gcode.push_str("(Generated by AutoCrate - too.foo/autocrate)\n\n");

    // Tool list
    gcode.push_str("(Tool List)\n");
    for tool in &program.tool_list {
        gcode.push_str(&format!(
            "(T{} - {} - {:.3}\" dia)\n",
            tool.tool_number, tool.tool_type, tool.diameter
        ));
    }
    gcode.push_str("\n");

    // Setup commands
    match units {
        GcodeUnits::Metric => gcode.push_str("G21 (Metric mode - millimeters)\n"),
        GcodeUnits::Imperial => gcode.push_str("G20 (Imperial mode - inches)\n"),
    }
    gcode.push_str("G90 (Absolute positioning)\n");
    gcode.push_str("G17 (XY plane selection)\n\n");

    // Process each operation
    for op in &program.operations {
        gcode.push_str(&format!(
            "(Operation {}: {})\n",
            op.operation_number, op.description
        ));
        gcode.push_str(&format!("M6 {} (Tool change)\n", op.tool));
        gcode.push_str(&format!(
            "S{} M3 (Spindle on at {} RPM)\n",
            op.spindle_speed, op.spindle_speed
        ));
        gcode.push_str("G4 P2.0 (Dwell 2 seconds for spindle to reach speed)\n\n");

        if let Some(first_point) = op.path.first() {
            // Rapid to start position above workpiece
            gcode.push_str(&format!(
                "G0 X{:.3} Y{:.3} Z10.000 (Rapid to start position)\n",
                first_point.x, first_point.y
            ));
            gcode.push_str("G0 Z2.000 (Approach height)\n");

            // Plunge to cutting depth
            gcode.push_str(&format!(
                "G1 Z-{:.3} F20.0 (Plunge to cutting depth)\n",
                op.cut_depth
            ));

            // Cut the path
            for (idx, point) in op.path.iter().enumerate().skip(1) {
                let feed_rate = if units == GcodeUnits::Metric {
                    op.feed_rate * 25.4 // Convert in/min to mm/min
                } else {
                    op.feed_rate
                };

                gcode.push_str(&format!(
                    "G1 X{:.3} Y{:.3} F{:.1} (Cut to point {})\n",
                    point.x,
                    point.y,
                    feed_rate,
                    idx + 1
                ));
            }

            // Retract
            gcode.push_str("G0 Z10.000 (Retract to safe height)\n");
        }

        gcode.push_str("M5 (Spindle off)\n\n");
    }

    // Program end
    gcode.push_str("M30 (Program end and rewind)\n");

    gcode
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geometry::*;

    fn create_test_program() -> CncCutProgram {
        CncCutProgram {
            operations: vec![CncOperation {
                operation_number: 1,
                operation_type: CncOperationType::OutlineProfile,
                tool: "T1".to_string(),
                feed_rate: 60.0,
                spindle_speed: 12000,
                cut_depth: 0.75,
                path: vec![
                    Point3 {
                        x: 0.0,
                        y: 0.0,
                        z: 0.0,
                    },
                    Point3 {
                        x: 48.0,
                        y: 0.0,
                        z: 0.0,
                    },
                    Point3 {
                        x: 48.0,
                        y: 36.0,
                        z: 0.0,
                    },
                    Point3 {
                        x: 0.0,
                        y: 36.0,
                        z: 0.0,
                    },
                    Point3 {
                        x: 0.0,
                        y: 0.0,
                        z: 0.0,
                    },
                ],
                description: "Front Panel - 48.0\" x 36.0\"".to_string(),
            }],
            tool_list: vec![CncTool {
                tool_number: 1,
                tool_type: "1/4\" End Mill".to_string(),
                diameter: 0.25,
            }],
            material_setup: "3/4\" Plywood".to_string(),
        }
    }

    #[test]
    fn test_gcode_imperial_mode() {
        let program = create_test_program();
        let gcode = export_cnc_gcode(&program, GcodeUnits::Imperial);

        // Check mode setting
        assert!(gcode.contains("G20 (Imperial mode"));

        // Check spindle commands
        assert!(gcode.contains("S12000 M3"));

        // Check feed rate in inches/min
        assert!(gcode.contains("F60."));

        // Check program end
        assert!(gcode.contains("M30"));
    }

    #[test]
    fn test_gcode_metric_mode() {
        let program = create_test_program();
        let gcode = export_cnc_gcode(&program, GcodeUnits::Metric);

        // Check mode setting
        assert!(gcode.contains("G21 (Metric mode"));

        // Feed rate should be converted to mm/min (60 * 25.4 = 1524)
        assert!(gcode.contains("F1524."));
    }

    #[test]
    fn test_gcode_structure() {
        let program = create_test_program();
        let gcode = export_cnc_gcode(&program, GcodeUnits::Imperial);

        // Check header
        assert!(gcode.contains("(AutoCrate CNC Program)"));
        assert!(gcode.contains("(Tool List)"));

        // Check setup
        assert!(gcode.contains("G90 (Absolute positioning)"));

        // Check tool change
        assert!(gcode.contains("M6 T1"));

        // Check path execution
        assert!(gcode.contains("G0 X0.000 Y0.000 Z10.000"));
        assert!(gcode.contains("G1 X48.000"));

        // Check spindle off
        assert!(gcode.contains("M5 (Spindle off)"));
    }

    #[test]
    fn test_rectangular_cut_path() {
        let program = create_test_program();
        let gcode = export_cnc_gcode(&program, GcodeUnits::Imperial);

        // Should cut a rectangle
        let lines: Vec<&str> = gcode.lines().collect();

        // Check corners are visited
        assert!(gcode.contains("X48.000 Y0.000"));
        assert!(gcode.contains("X48.000 Y36.000"));
        assert!(gcode.contains("X0.000 Y36.000"));
    }
}
